name: ldm2
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.9
  - pip=23.2.1
  - cudatoolkit=11.8.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - numpy=1.25.2
  - pip:
      - albumentations==1.3.0
      - opencv-python==4.8.0.74
      - imageio==2.31.1
      - imageio-ffmpeg==0.4.8
      - pytorch-lightning==1.4.2
      - omegaconf==2.3.0
      - test-tube>=0.7.5
      - streamlit==1.25.0
      - einops==0.6.1
      - transformers==4.31.0
      - webdataset==0.2.48
      - kornia==0.7.0
      - open_clip_torch==2.20.0
      - invisible-watermark>=0.2.0
      - streamlit-drawable-canvas==0.9.3
      - torchmetrics==0.6.0
      - -e .
